-- script.lua

function render()
    return [[
        <html>
        <body>
            <h1>Dynamic Content from Lua</h1>
            <p>This content is generated by a Lua script.</p>
        </body>
        </html>
    ]]
end
